<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121107062939 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE blog ADD user_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE blog ADD CONSTRAINT FK_C0155143A76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)");
        $this->addSql("CREATE INDEX IDX_C0155143A76ED395 ON blog (user_id)");
        $this->addSql("ALTER TABLE comment ADD user_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE comment ADD CONSTRAINT FK_9474526CA76ED395 FOREIGN KEY (user_id) REFERENCES fos_user (id)");
        $this->addSql("CREATE INDEX IDX_9474526CA76ED395 ON comment (user_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE blog DROP FOREIGN KEY FK_C0155143A76ED395");
        $this->addSql("DROP INDEX IDX_C0155143A76ED395 ON blog");
        $this->addSql("ALTER TABLE blog DROP user_id");
        $this->addSql("ALTER TABLE comment DROP FOREIGN KEY FK_9474526CA76ED395");
        $this->addSql("DROP INDEX IDX_9474526CA76ED395 ON comment");
        $this->addSql("ALTER TABLE comment DROP user_id");
    }
}
